# Generated by Django 2.2.4 on 2023-12-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0002_auto_20231202_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='confirm_passowrd',
            new_name='confirm_password',
        ),
    ]
