# Generated by Django 2.2.4 on 2023-11-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninja_shell_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
