# Generated by Django 2.2.4 on 2023-11-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='tittle',
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
